### PR TITLE
- removes peter from code owners

### PR DESCRIPTION
**Pull request by baywet**
- replaces baywet by coseguera since he is now the crew leader

### CODE REVIEW

**Comment by MaggieKimani1** [comment]
@baywet you're leaving us? 😢

**Comment by MaggieKimani1** [comment]
Ok that's completely understandable. It's been great working with you! 😁

**Comment by MaggieKimani1** [comment]
> @MaggieKimani1 not leaving the broader team no. But I'm at a place where my workload is just not manageable anymore. I've been struggling for months, and coming back from vacations, the backlog is growing faster than I can process items. Now that @coseguera is in charge of "OpenAPI libs" with a "crew", and he is a principal level person, I think it makes sense he takes one the responsibility to review code changes in this area moving forward.

Ok that's completely understandable. It's been great working with you! 😁

**Comment by baywet** [comment]
thanks! likewise! don't hesitate to send a perspective if you feel like so.

**Pull request merged**
