### PR TITLE
Set up API documentation with DocFX

### LINKED ISSUE #1026: Create API docs page for `Microsoft.OpenApi` package
I'm currently working on adding documentation on using the new `Microsoft.AspNetCore.OpenApi` package and am finding that I need to reference `Microsoft.OpenApi` types frequently. It would be great if there was a docs site for the package so that dependencies can link to them in their docs.

Let me know if this already exists!

### PR DESCRIPTION
**Pull request by MaggieKimani1**
- Sets up DocFX to generate API reference documentation from triple-slash/XML comments and build a static HTML website from our source code and Markdown files.
- Adds a Github action to deploy the static files generated to `gh-pages` for it to be hosted on the `github.io` web server
- Fixes #1026 

#### Generated documentation

 image

 image

### CODE REVIEW

**Review by baywet — CHANGES_REQUESTED** [review]
Isn't the doc fx content supposed to be under a separate repository under the Microsoft docs organization?
At least it's how we set it up for java core, PowerShell and dotnet core

**Comment by MaggieKimani1** [comment]
> Isn't the doc fx content supposed to be under a separate repository under the Microsoft docs organization? At least it's how we set it up for java core, PowerShell and dotnet core

I'm not aware of this. How do I go about it?

**Comment by baywet** [comment]
reached out privately with the details. Repo for java core is here for reference https://github.com/MicrosoftDocs/graph-core-docs-sdk-java

**Comment by MaggieKimani1** [comment]
> reached out privately with the details. Repo for java core is here for reference https://github.com/MicrosoftDocs/graph-core-docs-sdk-java

Thanks for the details. The java core repo link returns a 404 for me

**Comment by baywet** [comment]
It's probably because you don't have permissions to it. They assigned individual permissions back then instead of creating a group for our team. Let me know if you'd like me to try to grant you access

**Pull request closed without merging**
