### PR TITLE
Fixing the clipped graphic.

### PR DESCRIPTION
**Pull request by EricAtMSFT**
#artist #photoshoprookie

### CODE REVIEW

**Comment by PerthCharern** [comment]
@EricAtMSFT Isn't it still a little clipped at the top?

**Comment by EricAtMSFT** [comment]
Trying again....

**Comment by PerthCharern** [comment]
I think it looks okay now, but the top pixel is still a part of the circle, which makes it difficult for me to know for sure if something above that has been cut off.

Would it be possible if we ensure some space at the top of the logo, so that we can be 100% sure nothing is cut off?

**Comment by EricAtMSFT** [comment]
Just view it on my branch. Looks fine to me: https://github.com/Microsoft/OpenAPI.NET/tree/clipped-graphic

**Pull request merged**
