### PR TITLE
Bugfix#383 remove check for existence of discriminator property in the property list

### PR DESCRIPTION
**Pull request by senthilkumarmohan**

### CODE REVIEW

**Comment by senthilkumarmohan** [comment]
#383 is due to a validation rule added against anyOf/oneOf lists. I have removed this check as this check is not a MUST as per the spec. ref #376. Please can you review?

**Comment by PerthCharern** [comment]
>         }

@darrelmiller @senthilkumarmohan 

This is a bit tricky. The spec says this "The expectation now is that a property with name {discriminator.propertyName} MUST be present in the response payload". 

Should we interpret "MUST be present in the response payload" to mean "MUST be a required field"? There seems to be a nuanced difference here, whether intentionally or not. The original sentence in the spec talks about the response payload only and doesn't only say anything about the property or the field itself. (Compare this with another less ambiguous wording "As such, the discriminator field MUST be a required field.") 

I suggest we remove this check altogether.


---
Refers to: src/Microsoft.OpenApi/Validations/Rules/OpenApiSchemaRules.cs:139 in fcd74c4. [](commit_id = fcd74c49dfc2e11f3bfccc4f28419d691c637ea6, deletion_comment = False)

**Comment by PerthCharern** [comment]
>         }

Which means removing line 83-119 above too.

---
In reply to: [466162203](https://github.com/Microsoft/OpenAPI.NET/pull/384#issuecomment-466162203) [](ancestors = 466162203)

---
Refers to: src/Microsoft.OpenApi/Validations/Rules/OpenApiSchemaRules.cs:139 in fcd74c4. [](commit_id = fcd74c49dfc2e11f3bfccc4f28419d691c637ea6, deletion_comment = False)

**Comment by senthilkumarmohan** [comment]
I agree, will update the PR with suggested changes.

**Comment by senthilkumarmohan** [comment]
Hi @PerthCharern, I have updated the PR as suggested. Please can you review?

**Comment by PerthCharern** [comment]
Thanks for your continuous contribution @senthilkumarmohan!

**Pull request merged**
