### PR TITLE
Fix for writing DateTimeOffset values

### PR DESCRIPTION
**Pull request by darrelmiller**
Addresses #243

### CODE REVIEW

**Comment by darrelmiller** [comment]
@PerthCharern Any idea why we have this license/cla check that is holding up the PR?

**Comment by PerthCharern** [comment]
@darrelmiller 

It's required per Microsoft policy. The check evaluates whether a CLA needs to be signed (based on various factors like contributor(s), size of the change, etc.)

I have seen cases where it hangs up indefinitely for some reason. In that case, the fastest way to resolve it is to commit a new whitespace change.

**Comment by darrelmiller** [comment]
@PerthCharern I knew what it was, I just couldn't understand why it was an issue.  I'll try the whitespace trick.

**Comment by PerthCharern** [comment]
That I don't know. It started happening recently. I'll get in touch with the OSS team.

**Pull request merged**
