### PR TITLE
fixes#330-Yield validation err when an invalid security req key found

### PR DESCRIPTION
**Pull request by senthilkumarmohan**

### CODE REVIEW

**Comment by PerthCharern** [comment]
Thanks for the PR!

**Comment by PerthCharern** [comment]
@senthilkumarmohan  This will need to be merged into master as well since it's a bug fix. Could you create a duplicate PR from your branch but **merging into master**?

**Comment by PerthCharern** [comment]
@senthilkumarmohan Actually, I got that covered. :)

**Comment by senthilkumarmohan** [comment]
Thanks @PerthCharern

**Pull request merged**
