### PR TITLE
Use ConcurrentDictionary For Improving GetEnumFromDisplayName

### PR DESCRIPTION
**Pull request by Mahdigln**

### CODE REVIEW

**Comment by darrelmiller** [comment]
Is this change for perf reasons?  Do you have any benchmarks for what the perf difference is between these solutions?

**Comment by Mahdigln** [comment]
> Is this change for perf reasons? Do you have any benchmarks for what the perf difference is between these solutions?

I ran the benchmark with each method executed 1,000,000 times to simulate a high-usage scenario. This large number of iterations helps highlight the performance difference between the two approaches. Here's how the times break down:

    Without cache: 2230 ms for 1,000,000 executions.
    With cache: 63 ms for 1,000,000 executions.

This shows the significant advantage of using caching when dealing with repeated reflection operations

**Comment by darrelmiller** [comment]
That seems like a pretty significant improvement.  Thank you for the work.

**Review by darrelmiller — APPROVED** [review]

**Comment by Mahdigln** [comment]
> That seems like a pretty significant improvement. Thank you for the work.

Glad it was helpful! Hope to contribute more in the future.

**Pull request merged**
