### PR TITLE
Talamr/add document reader

### PR DESCRIPTION
**Pull request by talamram**
#298

### CODE REVIEW

**Comment by darrelmiller** [comment]
@talamram This looks good.  The only thing we have to be a bit concerned about is that I think this is the only place that we expose our usage of the SharpYaml package in our public API.  If we haven't already done that we need to decide if we want to tie our public interface to that library. I think currently, SharpYaml is an implementation detail.

**Comment by talamram** [comment]
Hi,
Unfortunetly, I can't deliver it since it turn out that I can't sign the CLA contract :( (my copmpany doesn't allow it).
If it look useful in your opinion, please deliver it.

Thanks!

**Comment by Jetski5822** [comment]
@talamram you explained to them that it’s in their interest to sign it?? Will benefit them...

**Comment by talamram** [comment]
Yes I did... Out of my control unfortunately

**Comment by darrelmiller** [comment]
@talamram Let me investigate if there is a way we can refactor some of the code in the StreamReader class so that you can create your own YamlDocumentReader without having to re-create all the initialization code.  Maybe if we moved some of the code into an abstract base class?

**Comment by darrelmiller** [comment]
There is now a YamlDocumentReader 
https://github.com/microsoft/OpenAPI.NET/blob/vnext/src/Microsoft.OpenApi.Readers/OpenApiYamlDocumentReader.cs

However, it is marked as internal.  We currently do not want to expose the dependency on this library publicly.  However, we may reconsider that decision.

**Pull request closed without merging**
