### PR TITLE
Visual Studio OpenAPI Document Converters

### PR DESCRIPTION
**Pull request by HowardvanRooijen**
A Visual Studio 2017 Custom Tool that converts between OpenAPI formats:

- to OpenAPI 2.0 JSON - Set Custom Tool to "ConvertToOpenApi_2_0_Json"
- to OpenAPI 2.0 YAML - Set Custom Tool to "ConvertToOpenApi_2_0_Yaml"
- to OpenAPI 3.0 JSON - Set Custom Tool to "ConvertToOpenApi_3_0_Json"
- to OpenAPI 3.0 YAML - Set Custom Tool to "ConvertToOpenApi_3_0_Yaml"

The primary usage scenario for this tool is the authoring of OpenAPI files in local Azure Function projects.

Also contains nice transparent background OpenAPI icon!

### CODE REVIEW

**Comment by darrelmiller** [comment]
Hey Howard!  This is great stuff.  Just the type of tooling I was hoping we could encourage with this library.  My question to you though is do you think that merging this into the core project is the best place for this tool.  All the PRs here require approval from another team member and we are a small team and likely to introduce latency in getting fixes into the tooling.

**Comment by HowardvanRooijen** [comment]
Hi Darrel!

More than happy for this to exist in its own repo. It would be lovely if once that was done there could be a link on the OpenAPI.NET SDK page to drive some traffic towards it.

I’m planning on doing something similar as a global tool.

**Comment by HowardvanRooijen** [comment]
I've moved the code to a new project https://github.com/endjin/Endjin.OpenAPI.Converters and published a v1.0 VSIX https://github.com/endjin/Endjin.OpenAPI.Converters/releases

**Comment by darrelmiller** [comment]
Awesome!  I will talk to the team about getting a link added to your tool.

**Pull request closed without merging**
