### PR TITLE
Updated package version to 1.0.0-beta017

### PR DESCRIPTION
**Pull request by darrelmiller**

### CODE REVIEW

**Comment by darrelmiller** [comment]
@PerthCharern Before merging this, I'd like to try disabling the auto deploy from AppVeyor and see if the VSTS deploy of the signed package works.

**Comment by PerthCharern** [comment]
No problem Darrel. Would you like me to turn that off, or will you do that yourself?

**Comment by PerthCharern** [comment]
If you are going to do it, I suggest we turn off the auto-deploy in GitHub (so that the push doesn't trigger appveyor) rather than turning off the deployment in AppVeyor. It's much easier to re-enable it later.

Just uncheck the "Active" box here: https://github.com/Microsoft/OpenAPI.NET/settings/hooks/18999895

**Comment by darrelmiller** [comment]
@PerthCharern I have turned off the AppVeyor hooks.  If you can approve this PR, I will merge and attempt to release from VSTS

**Comment by darrelmiller** [comment]
@PerthCharern @xuzhg Could someone approve this for me? Please :-)

**Pull request merged**
